name: GitHub Issues as WCAG result

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - labelled
      - unlabelled
  push:
    branches:
      - main
  # Schedule a daily check
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish-wcag-result:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Include GitHub Issues as WCAG result
        uses: frameless/wcag-issues-action@latest
        with:
          website: https://nldesignsystem.nl/
          label-color: D93F0B
          owner: nl-design-system
          repo: documentatie
          input: wcag-evaluation.json
          create-labels: true
          create-artifact: true
          token: ${{ secrets.GH_ISSUES_TOKEN }}
